############################################################
# Dockerfile to build Linux Apache PHP server with WordPress
# Based on the official mysql:mysql-server image
############################################################

    FROM ubuntu:18.04

    MAINTAINER nino <ninocangialosi@yahoo.it>

    ENV  DEBIAN_FRONTEND noninteractive
    RUN apt-get update && apt-get -y install apache2  wget
    #RUN docker-php-source extract && docker-php-ext-install mysqli && docker-php-source delete
    #RUN docker-php-ext-install mysqli
    RUN cd /var/www && wget http://wordpress.org/latest.tar.gz
    RUN tar -xzvf latest.tar.gz -C /var/www/
    RUN cp /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php
    RUN sed -i 's/'database_name_here'/getenv('DB_NAME')/' /var/www/wordpress/wp-config.php
    RUN sed -i 's/'username_here'/getenv('DB_USER')/' /var/www/wordpress/wp-config.php
    RUN sed -i 's/'database_password'/getenv('DB_PASSWORD')/' /var/www/wordpress/wp-config.php

    RUN sed -i 's/'localhost'/getenv('DB_HOST')/' wordpress/wp-config.php
    RUN cd /etc/apache2/sites-enabled/
    RUN sed -i 's/\/var\/www\/html/\/var\/www\/wordpress/' /etc/apache2/sites-enabled/000-default.conf

    EXPOSE 80

    CMD ['apache2ctl' ,' -D FOREGROUND']
