version: '3.3'

networks:
  my-net:

services:
   db:
     image: mysql:5.7
     volumes:
       - crv_mysql:/var/lib/mysql
     restart: always
     tty: true
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wordpress
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbpass
     volumes: ####here ask for how to do it properly
       - crv_mysql:/var/lib/mysql
     ports:
        - "3306:3306"
     networks:
       - my-net

   wordpress:
     depends_on:
       - db
     image: lapsrv:1.0
     ports:
       - "80:80"
     volumes: ['./:/var/www/html'] 
     restart: always
     environment:
       WORDPRESS_DB_HOST:  db:3306
       WORDPRESS_DB_USER: dbuser
       WORDPRESS_DB_PASSWORD: dbpass
       WORDPRESS_DB_NAME: wordpress
     networks:
       - my-net
volumes:
    crv_mysql: {}
